let tdwgCodes = {
  'Alabama': 'ala',
  'Alaska': 'ask',
  'Arizona': 'ari',
  'Arkansas': 'ark',
  'California': 'cal',
  'Colorado': 'col',
  'Connecticut': 'con',
  'Delaware': 'del',
  'Florida': 'flo',
  'Georgia': 'geo',
  'Hawaii': 'haw',
  'Idaho': 'ida',
  'Illinois': 'ill',
  'Indiana': 'ind',
  'Iowa': 'iow',
  'Kansas': 'kan',
  'Kentucky': 'ken',
  'Louisiana': 'lou',
  'Maine': 'mai',
  'Maryland': 'mar',
  'Massachusetts': 'mas',
  'Michigan': 'mic',
  'Minnesota': 'min',
  'Mississippi': 'msi',
  'Missouri': 'mso',
  'Montana': 'mon',
  'Nebraska': 'neb',
  'Nevada': 'nev',
  'New Hampshire': 'nwh',
  'New Jersey': 'nwj',
  'New Mexico': 'nwm',
  'New York': 'nwy',
  'North Carolina': 'nca',
  'North Dakota': 'nda',
  'Ohio': 'ohi',
  'Oklahoma': 'okl',
  'Oregon': 'ore',
  'Pennsylvania': 'pen',
  'Rhode Island': 'rho',
  'South Carolina': 'sca',
  'South Dakota': 'sda',
  'Tennessee': 'ten',
  'Texas': 'tex',
  'Utah': 'uta',
  'Vermont': 'ver',
  'Virginia': 'vig',
  'Washington': 'was',
  'West Virginia': 'wes',
  'Wisconsin': 'wis',
  'Wyoming': 'wyo'
}

export default {
  tdwgCodes
}